// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/rep_tracker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RepTrackerService_AddTrackingRepo_FullMethodName    = "/rep_tracker.RepTrackerService/AddTrackingRepo"
	RepTrackerService_RemoveTrackingRepo_FullMethodName = "/rep_tracker.RepTrackerService/RemoveTrackingRepo"
)

// RepTrackerServiceClient is the client API for RepTrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepTrackerServiceClient interface {
	AddTrackingRepo(ctx context.Context, in *TrackingRepo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveTrackingRepo(ctx context.Context, in *TrackingRepo, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type repTrackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepTrackerServiceClient(cc grpc.ClientConnInterface) RepTrackerServiceClient {
	return &repTrackerServiceClient{cc}
}

func (c *repTrackerServiceClient) AddTrackingRepo(ctx context.Context, in *TrackingRepo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RepTrackerService_AddTrackingRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repTrackerServiceClient) RemoveTrackingRepo(ctx context.Context, in *TrackingRepo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RepTrackerService_RemoveTrackingRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepTrackerServiceServer is the server API for RepTrackerService service.
// All implementations must embed UnimplementedRepTrackerServiceServer
// for forward compatibility.
type RepTrackerServiceServer interface {
	AddTrackingRepo(context.Context, *TrackingRepo) (*emptypb.Empty, error)
	RemoveTrackingRepo(context.Context, *TrackingRepo) (*emptypb.Empty, error)
	mustEmbedUnimplementedRepTrackerServiceServer()
}

// UnimplementedRepTrackerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepTrackerServiceServer struct{}

func (UnimplementedRepTrackerServiceServer) AddTrackingRepo(context.Context, *TrackingRepo) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTrackingRepo not implemented")
}
func (UnimplementedRepTrackerServiceServer) RemoveTrackingRepo(context.Context, *TrackingRepo) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTrackingRepo not implemented")
}
func (UnimplementedRepTrackerServiceServer) mustEmbedUnimplementedRepTrackerServiceServer() {}
func (UnimplementedRepTrackerServiceServer) testEmbeddedByValue()                           {}

// UnsafeRepTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepTrackerServiceServer will
// result in compilation errors.
type UnsafeRepTrackerServiceServer interface {
	mustEmbedUnimplementedRepTrackerServiceServer()
}

func RegisterRepTrackerServiceServer(s grpc.ServiceRegistrar, srv RepTrackerServiceServer) {
	// If the following call panics, it indicates UnimplementedRepTrackerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RepTrackerService_ServiceDesc, srv)
}

func _RepTrackerService_AddTrackingRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackingRepo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepTrackerServiceServer).AddTrackingRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepTrackerService_AddTrackingRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepTrackerServiceServer).AddTrackingRepo(ctx, req.(*TrackingRepo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepTrackerService_RemoveTrackingRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackingRepo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepTrackerServiceServer).RemoveTrackingRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepTrackerService_RemoveTrackingRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepTrackerServiceServer).RemoveTrackingRepo(ctx, req.(*TrackingRepo))
	}
	return interceptor(ctx, in, info, handler)
}

// RepTrackerService_ServiceDesc is the grpc.ServiceDesc for RepTrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepTrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rep_tracker.RepTrackerService",
	HandlerType: (*RepTrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTrackingRepo",
			Handler:    _RepTrackerService_AddTrackingRepo_Handler,
		},
		{
			MethodName: "RemoveTrackingRepo",
			Handler:    _RepTrackerService_RemoveTrackingRepo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rep_tracker.proto",
}
