// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/rep_tracker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackingRepo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingRepo) Reset() {
	*x = TrackingRepo{}
	mi := &file_proto_rep_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingRepo) ProtoMessage() {}

func (x *TrackingRepo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rep_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingRepo.ProtoReflect.Descriptor instead.
func (*TrackingRepo) Descriptor() ([]byte, []int) {
	return file_proto_rep_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *TrackingRepo) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *TrackingRepo) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

var File_proto_rep_tracker_proto protoreflect.FileDescriptor

const file_proto_rep_tracker_proto_rawDesc = "" +
	"\n" +
	"\x17proto/rep_tracker.proto\x12\vrep_tracker\x1a\x1bgoogle/protobuf/empty.proto\";\n" +
	"\fTrackingRepo\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId2\xa2\x01\n" +
	"\x11RepTrackerService\x12D\n" +
	"\x0fAddTrackingRepo\x12\x19.rep_tracker.TrackingRepo\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x12RemoveTrackingRepo\x12\x19.rep_tracker.TrackingRepo\x1a\x16.google.protobuf.EmptyB\x19Z\x17rep_tracker/proto;protob\x06proto3"

var (
	file_proto_rep_tracker_proto_rawDescOnce sync.Once
	file_proto_rep_tracker_proto_rawDescData []byte
)

func file_proto_rep_tracker_proto_rawDescGZIP() []byte {
	file_proto_rep_tracker_proto_rawDescOnce.Do(func() {
		file_proto_rep_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rep_tracker_proto_rawDesc), len(file_proto_rep_tracker_proto_rawDesc)))
	})
	return file_proto_rep_tracker_proto_rawDescData
}

var file_proto_rep_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_rep_tracker_proto_goTypes = []any{
	(*TrackingRepo)(nil),  // 0: rep_tracker.TrackingRepo
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_proto_rep_tracker_proto_depIdxs = []int32{
	0, // 0: rep_tracker.RepTrackerService.AddTrackingRepo:input_type -> rep_tracker.TrackingRepo
	0, // 1: rep_tracker.RepTrackerService.RemoveTrackingRepo:input_type -> rep_tracker.TrackingRepo
	1, // 2: rep_tracker.RepTrackerService.AddTrackingRepo:output_type -> google.protobuf.Empty
	1, // 3: rep_tracker.RepTrackerService.RemoveTrackingRepo:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rep_tracker_proto_init() }
func file_proto_rep_tracker_proto_init() {
	if File_proto_rep_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rep_tracker_proto_rawDesc), len(file_proto_rep_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rep_tracker_proto_goTypes,
		DependencyIndexes: file_proto_rep_tracker_proto_depIdxs,
		MessageInfos:      file_proto_rep_tracker_proto_msgTypes,
	}.Build()
	File_proto_rep_tracker_proto = out.File
	file_proto_rep_tracker_proto_goTypes = nil
	file_proto_rep_tracker_proto_depIdxs = nil
}
