// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: coder_manager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoderManagerService_CreateEditorSession_FullMethodName = "/coder_manager.CoderManagerService/CreateEditorSession"
)

// CoderManagerServiceClient is the client API for CoderManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoderManagerServiceClient interface {
	CreateEditorSession(ctx context.Context, in *CreateEditorSessionRequest, opts ...grpc.CallOption) (*CreateEditorSessionResponse, error)
}

type coderManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoderManagerServiceClient(cc grpc.ClientConnInterface) CoderManagerServiceClient {
	return &coderManagerServiceClient{cc}
}

func (c *coderManagerServiceClient) CreateEditorSession(ctx context.Context, in *CreateEditorSessionRequest, opts ...grpc.CallOption) (*CreateEditorSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEditorSessionResponse)
	err := c.cc.Invoke(ctx, CoderManagerService_CreateEditorSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoderManagerServiceServer is the server API for CoderManagerService service.
// All implementations must embed UnimplementedCoderManagerServiceServer
// for forward compatibility.
type CoderManagerServiceServer interface {
	CreateEditorSession(context.Context, *CreateEditorSessionRequest) (*CreateEditorSessionResponse, error)
	mustEmbedUnimplementedCoderManagerServiceServer()
}

// UnimplementedCoderManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoderManagerServiceServer struct{}

func (UnimplementedCoderManagerServiceServer) CreateEditorSession(context.Context, *CreateEditorSessionRequest) (*CreateEditorSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEditorSession not implemented")
}
func (UnimplementedCoderManagerServiceServer) mustEmbedUnimplementedCoderManagerServiceServer() {}
func (UnimplementedCoderManagerServiceServer) testEmbeddedByValue()                             {}

// UnsafeCoderManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoderManagerServiceServer will
// result in compilation errors.
type UnsafeCoderManagerServiceServer interface {
	mustEmbedUnimplementedCoderManagerServiceServer()
}

func RegisterCoderManagerServiceServer(s grpc.ServiceRegistrar, srv CoderManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedCoderManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoderManagerService_ServiceDesc, srv)
}

func _CoderManagerService_CreateEditorSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEditorSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoderManagerServiceServer).CreateEditorSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoderManagerService_CreateEditorSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoderManagerServiceServer).CreateEditorSession(ctx, req.(*CreateEditorSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoderManagerService_ServiceDesc is the grpc.ServiceDesc for CoderManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoderManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coder_manager.CoderManagerService",
	HandlerType: (*CoderManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEditorSession",
			Handler:    _CoderManagerService_CreateEditorSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coder_manager.proto",
}
