// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/coder_manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEditorSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	ChatId        string                 `protobuf:"bytes,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEditorSessionRequest) Reset() {
	*x = CreateEditorSessionRequest{}
	mi := &file_proto_coder_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEditorSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEditorSessionRequest) ProtoMessage() {}

func (x *CreateEditorSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coder_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEditorSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateEditorSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_coder_manager_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEditorSessionRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *CreateEditorSessionRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateEditorSessionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateEditorSessionRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CreateEditorSessionRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateEditorSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OneTimeUrl    string                 `protobuf:"bytes,1,opt,name=one_time_url,json=oneTimeUrl,proto3" json:"one_time_url,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEditorSessionResponse) Reset() {
	*x = CreateEditorSessionResponse{}
	mi := &file_proto_coder_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEditorSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEditorSessionResponse) ProtoMessage() {}

func (x *CreateEditorSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coder_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEditorSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateEditorSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_coder_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEditorSessionResponse) GetOneTimeUrl() string {
	if x != nil {
		return x.OneTimeUrl
	}
	return ""
}

func (x *CreateEditorSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateEditorSessionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_proto_coder_manager_proto protoreflect.FileDescriptor

const file_proto_coder_manager_proto_rawDesc = "" +
	"\n" +
	"\x19proto/coder_manager.proto\x12\rcoder_manager\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n" +
	"\x1aCreateEditorSessionRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\tR\x06chatId\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\"\x99\x01\n" +
	"\x1bCreateEditorSessionResponse\x12 \n" +
	"\fone_time_url\x18\x01 \x01(\tR\n" +
	"oneTimeUrl\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\x83\x01\n" +
	"\x13CoderManagerService\x12l\n" +
	"\x13CreateEditorSession\x12).coder_manager.CreateEditorSessionRequest\x1a*.coder_manager.CreateEditorSessionResponseB\x1fZ\x1dcoder_manager/pkg/proto;protob\x06proto3"

var (
	file_proto_coder_manager_proto_rawDescOnce sync.Once
	file_proto_coder_manager_proto_rawDescData []byte
)

func file_proto_coder_manager_proto_rawDescGZIP() []byte {
	file_proto_coder_manager_proto_rawDescOnce.Do(func() {
		file_proto_coder_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coder_manager_proto_rawDesc), len(file_proto_coder_manager_proto_rawDesc)))
	})
	return file_proto_coder_manager_proto_rawDescData
}

var file_proto_coder_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_coder_manager_proto_goTypes = []any{
	(*CreateEditorSessionRequest)(nil),  // 0: coder_manager.CreateEditorSessionRequest
	(*CreateEditorSessionResponse)(nil), // 1: coder_manager.CreateEditorSessionResponse
	(*timestamppb.Timestamp)(nil),       // 2: google.protobuf.Timestamp
}
var file_proto_coder_manager_proto_depIdxs = []int32{
	2, // 0: coder_manager.CreateEditorSessionResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: coder_manager.CoderManagerService.CreateEditorSession:input_type -> coder_manager.CreateEditorSessionRequest
	1, // 2: coder_manager.CoderManagerService.CreateEditorSession:output_type -> coder_manager.CreateEditorSessionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_coder_manager_proto_init() }
func file_proto_coder_manager_proto_init() {
	if File_proto_coder_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coder_manager_proto_rawDesc), len(file_proto_coder_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coder_manager_proto_goTypes,
		DependencyIndexes: file_proto_coder_manager_proto_depIdxs,
		MessageInfos:      file_proto_coder_manager_proto_msgTypes,
	}.Build()
	File_proto_coder_manager_proto = out.File
	file_proto_coder_manager_proto_goTypes = nil
	file_proto_coder_manager_proto_depIdxs = nil
}
